{% set name = "cryptoauthlib" %}
{% set version = "20211006" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cryptoauthlib-{{ version }}.tar.gz
  sha256: dd524325922677defbbf737956be08ae501d12546d0e61eaf0d5ba48e1f90fe4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - cmake
    - {{ cdt('libudev-devel') }}  # [linux and cdt_name=='cos6']
    - {{ cdt('systemd-devel') }}  # [linux and cdt_name=='cos7']
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=38.6.0
    - wheel
  run:
    - enum34  # [py<34]
    - patchelf  # [linux]
    - libusb  # [linux]
    - python

test:
  imports:
    - cryptoauthlib
  commands:
    - python -c "from cryptoauthlib.library import get_size_by_name; get_size_by_name('ATCAIfaceCfg')"

about:
  home: https://github.com/MicrochipTech/cryptoauthlib
  summary: Python Wrapper Library for Microchip Security Products
  dev_url: https://github.com/MicrochipTech/cryptoauthlib
  license: Proprietary
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bryan-hunt
    - KalyanCManukonda
