{% set name = "cryptoauthlib" %}
{% set version = "20210512" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cryptoauthlib-{{ version }}.tar.gz
  sha256: f16c42313c9a18566794c6bf07ac60fbf1824e9ff3a79791ad368b646f05b006

build:
  number: 0
  skip: true  # [linux]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=38.6.0
    - wheel
  run:
    - enum34  # [py<34]
    - python

test:
  imports:
    - cryptoauthlib
  commands:
    - python -c "from cryptoauthlib.library import get_size_by_name; get_size_by_name('ATCAIfaceCfg')"

about:
  home: https://github.com/MicrochipTech/cryptoauthlib
  summary: Python Wrapper Library for Microchip Security Products
  dev_url: https://github.com/MicrochipTech/cryptoauthlib
  license: Proprietary
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bryan-hunt
    - KalyanCManukonda
