{% set name = "cryptoauthlib" %}
{% set version = "20260505" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cryptoauthlib-{{ version }}.tar.gz
  sha256: 34ced301cfba7e58b13f6a423d9afa520c0bd28f6ec933ce79bb37c1ca558fc7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - cmake
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools >=38.6.0
    - wheel
    - libudev
    - libsystemd
  run:
    - patchelf  # [linux]
    - python

test:
  imports:
    - cryptoauthlib
  commands:
    - python -c "from cryptoauthlib.library import get_size_by_name; get_size_by_name('ATCAIfaceCfg')"

about:
  home: https://github.com/MicrochipTech/cryptoauthlib
  summary: Python Wrapper Library for Microchip Security Products
  dev_url: https://github.com/MicrochipTech/cryptoauthlib
  license: Proprietary
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bryan-hunt
    - KalyanCManukonda
