{% set name = "cryptoauthlib" %}
{% set version = "20221114" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cryptoauthlib-{{ version }}.tar.gz
  sha256: cc63dba63f1983c12ad18ecb3f1595083feffc0cb827d2a8d3a54c850d26ed5d

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - make  # [linux]
    - libudev  # [linux]
    - cmake
    - {{ cdt('libudev-devel') }}  # [linux and cdt_name=='cos6']
    - {{ cdt('systemd-devel') }}  # [linux and cdt_name=='cos7']
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools >=38.6.0
    - wheel
  run:
    - enum34  # [py<34]
    - patchelf  # [linux]
    - libudev  # [linux]
    - python

test:
  imports:
    - cryptoauthlib
  commands:
    - python -c "from cryptoauthlib.library import get_size_by_name; get_size_by_name('ATCAIfaceCfg')"

about:
  home: https://github.com/MicrochipTech/cryptoauthlib
  summary: Python Wrapper Library for Microchip Security Products
  dev_url: https://github.com/MicrochipTech/cryptoauthlib
  license: Proprietary
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bryan-hunt
    - KalyanCManukonda
